config:
    name: Snowlanuck's Blog.
    description: This is Snowlanuck's Blog.
    link: https://snowlnauck.github.io/
    image:
    copyright:
    branch: master
    domain: https://snowlanuck.github.io/
    email: snowlanuck@gmail.com
    repository: snowlanuck.github.io
    token:
    username: Snowlanuck
    theme: Satkiryuin

comment:
    commentPlatform: gitalk
    disqusSetting:
        api:
        apikey:
        shortname:
    gitalkSetting: 
        clientId:
        clientSecret:
        owner:
        repository:
    showComment: false